title: Resources for Open Science in Astronomy (ROSA)
subtitle:
email: rachael.ainsworth@manchester.ac.uk
twitter: https://twitter.com/rachaelevelyn
chat: https://gitter.im/Resources-Open-Science-Astronomy/Lobby
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sed
  condimentum libero. Phasellus cursus, dui eu dictum interdum, velit mauris
  sodales odio, elementum congue elit metus eu quam.
baseurl: "/ROSA" # the subpath of your site, e.g. /blog
url: "https://rainsworth.github.io" # the base hostname & protocol for your site
github:
  repo: "rainsworth/ROSA"
  branch: "gh-pages"


collections:
  articles:
    output: true
permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]

# variables
video: "<span class=\"video-player\"></span>"
assignment: "<span class=\"assignment\">Assignment: </span>"
